k8s_scale - add option label_selectors and continue_on_error
ansible-collections/kubernetes.core pull request #114
Opened 2021-05-25 14:31 UTC by abikouo

##### SUMMARY

``k8s_scale`` - add new parameter ``label_selectors`` to support scale for multiple resources, and new parameter ``continue_on_error`` to determine wether to continue with others resources when an error occurs.

#112 
##### ISSUE TYPE

- Feature Pull Request
##### COMPONENT NAME

k8s_scale
##### ADDITIONAL INFORMATION

```paste below
- kubernetes.core.k8s_scale:
  kind: Deployment
  namespace: default
  label_selectors:
    - app = test
  replicas: 3
```

2021-06-01 06:18 UTC, Akasurde commented on changelogs/fragments/114-k8s_scale-add-label-selectors-and-continue-on-error.yaml
> +  - k8s_scale - new parameter to determine wether to continue or not on error when scaling multiple resources (https://github.com/ansible-collections/community.kubernetes/pull/114).
```suggestion
  - k8s_scale - new parameter to determine whether to continue or not on error when scaling multiple resources (https://github.com/ansible-collections/community.kubernetes/pull/114).
```

2021-06-01 06:19 UTC, Akasurde commented on molecule/default/tasks/scale.yml
> +          - resource.resources | list | length == 2
```suggestion
          - resource.resources | list | length == 2
          - resource is changed
```

2021-06-01 06:20 UTC, Akasurde commented on plugins/modules/k8s_scale.py
> +    description: List of label selectors to use to filter results
```suggestion
    description: List of label selectors to use to filter results.
```

2021-06-01 06:22 UTC, Akasurde commented on plugins/modules/k8s_scale.py
> +      - app = test
Since this is string I would avoid spaces in between 

```suggestion
      - app=test
```

2021-06-01 06:23 UTC, Akasurde requested changes
Rest LGTM

2021-06-03 17:40 UTC, gravesm approved these changes

2021-06-07 07:57 UTC, merged