Docs: Migrate Scenario Guide to collection
ansible-collections/kubernetes.core pull request #143
Opened 2021-06-22 05:58 UTC by Akasurde

##### SUMMARY

Migrate scenario guide from ansible/ansible repo to
this collection.

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
docs/docsite/rst/kubernetes_scenarios/k8s_intro.rst
docs/docsite/rst/kubernetes_scenarios/k8s_inventory.rst
docs/docsite/rst/kubernetes_scenarios/k8s_scenarios.rst
docs/docsite/rst/kubernetes_scenarios/scenario_k8s_object.rst
docs/docsite/rst/scenario_guide.rst

2021-06-29 13:05 UTC, gravesm requested changes

2021-06-29 13:05 UTC, gravesm commented on docs/docsite/rst/kubernetes_scenarios/scenario_k8s_object.rst
> +- community.kubernetes 1.1.0 is going to migrate to `kubernetes.core <https://github.com/ansible-collections/kubernetes.core>`_
```suggestion
- community.kubernetes 2.0.0 has been renamed to `kubernetes.core <https://github.com/ansible-collections/kubernetes.core>`_
```

2021-06-29 13:05 UTC, gravesm commented on docs/docsite/rst/kubernetes_scenarios/scenario_k8s_object.rst
> +        The issue tracker for OpenShift Dynamic API client
```suggestion
```

2021-07-08 09:06 UTC, felixfontein commented
You might want to add a call to `antsibull-lint collection-docs` to CI for this. It will run rstcheck on the `.rst` files, make sure that `docs/docsite/extra-docs.yml` looks good, and that the labels in the `.rst` files are correctly prefixed.

2021-07-08 10:09 UTC, Akasurde commented
> You might want to add a call to `antsibull-lint collection-docs` to CI for this. It will run rstcheck on the `.rst` files, make sure that `docs/docsite/extra-docs.yml` looks good, and that the labels in the `.rst` files are correctly prefixed.

I will raise a separate CI PR to address this. Thanks for the feedback.

2021-07-08 14:49 UTC, gravesm approved these changes

2021-07-09 04:25 UTC, merged