k8s support diff mode (breaking changes)
ansible-collections/kubernetes.core pull request #146
Opened 2021-06-23 15:34 UTC by abikouo

##### SUMMARY

``diff`` attribute was always returned in output when ``k8s`` module was executed using options, ``force``, ``apply`` or ``state=patched`` even if the ``diff=no`` was set at task level.
This fix aims to correct this
#88 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

k8s

2021-07-12 13:26 UTC, gravesm requested changes
Just realized we also need to fix the `k8s_scale` and `k8s_json_patch` modules, too.

2021-07-12 13:26 UTC, gravesm commented on changelogs/fragments/146-k8s-add-support-diff-mode.yml
> +  - k8s - Add support for diff mode, diff is returned only when it is explicitly requested (https://github.com/ansible-collections/kubernetes.core/pull/146).
```suggestion
  - k8s - Fixes a bug where diff was always returned when using apply or modifying an existing object, even when diff=no was specified. The module no longer returns diff unless requested and will now honor diff=no (https://github.com/ansible-collections/kubernetes.core/pull/146).
```

2021-07-19 18:59 UTC, gravesm commented
> Just realized we also need to fix the k8s_scale and k8s_json_patch modules, too.

This still needs to be addressed.

2021-07-20 10:07 UTC, abikouo commented
> > Just realized we also need to fix the k8s_scale and k8s_json_patch modules, too.
> 
> This still needs to be addressed.

done

2021-07-20 17:46 UTC, gravesm approved these changes
Thanks!

2021-07-21 12:29 UTC, merged