k8s - add label_selectors options
ansible-collections/kubernetes.core pull request #158
Opened 2021-06-30 15:42 UTC by abikouo

##### SUMMARY
``k8s`` now support ``label_selectors`` options same as ``k8s_info``

Resolves #43 

##### ISSUE TYPE

- Feature Pull Request
- 
##### COMPONENT NAME

k8s

2021-07-08 17:36 UTC, gravesm requested changes
The label_selector on the k8s module should support the same functionality as the label_selector on the k8s_info module, otherwise, it's going to be confusing. Specifically, we need to add set support for set-based requirements. See https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors.

2021-07-08 17:36 UTC, gravesm commented on plugins/module_utils/common.py
> +                    result['warning'] = "resource 'kind={kind},name={name},namespace={namespace}' filtered by label_selectors.".format(
This isn't really a warning because it's exactly what the user requested. I'd suggest we instead use `msg` here.

2021-07-08 17:36 UTC, gravesm commented on plugins/module_utils/common.py
> +                    del result['result']
If we delete the result key, this is a breaking change. It should just be an empty dict.

2021-07-19 15:03 UTC, abikouo commented
> The label_selector on the k8s module should support the same functionality as the label_selector on the k8s_info module, otherwise, it's going to be confusing. Specifically, we need to add support for set-based requirements. See https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors.

ok this is not supporting set-based requirement now as there are some filters performed locally, it would be great to have this directly done on kubernetes python client. I will work on it

2021-07-27 13:52 UTC, abikouo commented
recheck

2021-07-27 14:17 UTC, abikouo commented on plugins/module_utils/selector.py
> +class Selector(object):
Thats true, will try this
Thanks

2021-07-28 18:31 UTC, gravesm approved these changes

2021-07-29 09:56 UTC, merged