helm: add support for history-max parameter
ansible-collections/kubernetes.core pull request #164
Opened 2021-07-08 08:40 UTC by vvanouytsel

##### SUMMARY
The --history-max parameter allows the user to set a maximum amount of
revisions per release to be kept in the history.

By default helm keeps 10 revisions per release, which means that 10
secrets will be kept per release. If you have multiple helm releases, the amount of secrets created by Helm will quickly add up.

With supporting the 'history-max' CLI parameter via the ansible module, the user will have the posibility to determine how many revisions he wants to keep per release.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
plugins/modules/helm.py

##### ADDITIONAL INFORMATION

**Before change:**
```yaml
- name: example
  hosts: localhost
  tasks:
    - name: "Deploy helm chart before change"
      kubernetes.core.helm:
        name: "example"
        chart_ref: "/tmp/example"
        release_namespace: default
        wait_timeout: 10m
```
```
PLAY [example] ***********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Deploy helm chart before change] ***********************************************************************************************************************************************************************************************
changed: [localhost] => {"changed": true, "command": "/usr/bin/helm upgrade -i --reset-values example /tmp/example", "status": {"app_version": "3.0.0", "chart": "example-3.0.0", "name": "example", "namespace": "default", "revision": "1", "status": "deployed", "updated": "2021-07-08 08:38:47.591116754 +0000 UTC", "values": {}}, "stderr": "", "stderr_lines": [], "stdout": "Release \"example\" does not exist. Installing it now.\nNAME: example\nLAST DEPLOYED: Thu Jul  8 08:38:47 2021\nNAMESPACE: default\nSTATUS: deployed\nREVISION: 1\nTEST SUITE: None\nNOTES:\nDeployed!\n", "stdout_lines": ["Release \"example\" does not exist. Installing it now.", "NAME: example", "LAST DEPLOYED: Thu Jul  8 08:38:47 2021", "NAMESPACE: default", "STATUS: deployed", "REVISION: 1", "TEST SUITE: None", "NOTES:", "Deployed!"]}

PLAY RECAP ***************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

**After change:**
Without history_max  set:
```yaml
- name: example
  hosts: localhost
  tasks:
    - name: "Deploy helm chart without history_max"
      kubernetes.core.helm:
        name: "example"
        chart_ref: "/tmp/example"
        release_namespace: default
        wait_timeout: 10m
```
```
PLAY [example] ***********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Deploy helm chart without history_max] *****************************************************************************************************************************************************************************************
changed: [localhost] => {"changed": true, "command": "/usr/bin/helm upgrade -i --reset-values --history-max=10 example /tmp/example", "status": {"app_version": "3.0.0", "chart": "example-3.0.0", "name": "example", "namespace": "default", "revision": "1", "status": "deployed", "updated": "2021-07-08 08:33:24.728443982 +0000 UTC", "values": {}}, "stderr": "", "stderr_lines": [], "stdout": "Release \"example\" does not exist. Installing it now.\nNAME: example\nLAST DEPLOYED: Thu Jul  8 08:33:24 2021\nNAMESPACE: default\nSTATUS: deployed\nREVISION: 1\nTEST SUITE: None\nNOTES:\nDeployed!\n", "stdout_lines": ["Release \"example\" does not exist. Installing it now.", "NAME: example", "LAST DEPLOYED: Thu Jul  8 08:33:24 2021", "NAMESPACE: default", "STATUS: deployed", "REVISION: 1", "TEST SUITE: None", "NOTES:", "Deployed!"]}

PLAY RECAP ***************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 
 ```

With history_max set:
```yaml
- name: example
  hosts: localhost
  tasks:
    - name: "Deploy helm chart with history_max"
      kubernetes.core.helm:
        name: "example"
        chart_ref: "/tmp/example"
        release_namespace: default
        wait_timeout: 10m
        history_max: 3
```
```
PLAY [example] ***********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Deploy helm chart with history_max] ********************************************************************************************************************************************************************************************
changed: [localhost] => {"changed": true, "command": "/usr/bin/helm upgrade -i --reset-values --history-max=3 example /tmp/example", "status": {"app_version": "3.0.0", "chart": "example-3.0.0", "name": "example", "namespace": "default", "revision": "1", "status": "deployed", "updated": "2021-07-08 08:35:28.231751834 +0000 UTC", "values": {}}, "stderr": "", "stderr_lines": [], "stdout": "Release \"example\" does not exist. Installing it now.\nNAME: example\nLAST DEPLOYED: Thu Jul  8 08:35:28 2021\nNAMESPACE: default\nSTATUS: deployed\nREVISION: 1\nTEST SUITE: None\nNOTES:\nDeployed!\n", "stdout_lines": ["Release \"example\" does not exist. Installing it now.", "NAME: example", "LAST DEPLOYED: Thu Jul  8 08:35:28 2021", "NAMESPACE: default", "STATUS: deployed", "REVISION: 1", "TEST SUITE: None", "NOTES:", "Deployed!"]}

PLAY RECAP ***************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```

2021-07-09 04:22 UTC, Akasurde commented on plugins/modules/helm.py
> +    version_added: "2.1.2"
```suggestion
    version_added: "2.2.0"
```

This will go in minor release rather than in patch release.

2021-07-09 04:25 UTC, Akasurde commented on plugins/modules/helm.py
> +    deploy_command +=  " --history-max=" + str(history_max) + " " + release_name + " " + chart_name
```suggestion
    if history_max: 
        deploy_command += " --history-max=%s" % str(history_max)

    deploy_command += " " + release_name + " " + chart_name
```

2021-07-09 04:25 UTC, Akasurde commented on plugins/modules/helm.py
> +    default: False
Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment). See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

2021-07-13 10:47 UTC, vvanouytsel commented
Thanks for you review @Akasurde , I've added your remarks to the PR.
If you have any more remarks please let them know.

Thanks!

2021-07-13 15:09 UTC, abikouo approved these changes

2021-07-15 07:15 UTC, vvanouytsel commented
Thanks for reviewing @abikouo!
Are you able to approve the workflow for this PR as well?

2021-07-15 07:59 UTC, abikouo commented
> Thanks for reviewing @abikouo!
> Are you able to approve the workflow for this PR as well?

Should be ok now.

2021-07-15 12:18 UTC, gravesm requested changes
@vvanouytsel Thank you for the PR! The `--history-max` option is not supported for `helm install` which is used when the `replace` param is set. The `history_max` and `replace` parameters will need to be set to mutually exclusive. This can be done here: https://github.com/ansible-collections/kubernetes.core/blob/b32e5cd06fa90d2d27df3008a421b46fd7983942/plugins/modules/helm.py#L554 and also by updating the documentation for each parameter, an example of which is here: https://github.com/ansible-collections/kubernetes.core/blob/b32e5cd06fa90d2d27df3008a421b46fd7983942/plugins/modules/k8s.py#L65

2021-07-15 13:53 UTC, vvanouytsel commented
@gravesm Thanks for your review!
I have fixed the linting issue and have also added both 'replace' and 'history_max' to the 'mutually_exclusive' parameter.
Let me know if you require any more changes.

2021-07-15 15:01 UTC, gravesm requested changes
A few small nits and then everything else looks good.

2021-07-15 17:20 UTC, gravesm approved these changes
Thanks @vvanouytsel!

2021-07-15 17:21 UTC, merged