[connection plugin] add missing information from censored command
ansible-collections/kubernetes.core pull request #196
Opened 2021-07-30 15:48 UTC by abikouo

##### SUMMARY
when running playbook with ``vvv`` option, the censored command display is not reflecting the execution

##### ISSUE TYPE

- Bugfix Pull Request

2021-08-02 13:49 UTC, gravesm requested changes

2021-08-02 13:49 UTC, gravesm commented on changelogs/fragments/196_kubectl.yaml
> +- connection plugin - add arguments information into censored command. (https://github.com/ansible-collections/kubernetes.core/issues/147).
This links to an unrelated issue.

2021-08-03 09:14 UTC, abikouo commented
recheck

2021-08-03 15:16 UTC, gravesm commented on changelogs/fragments/196_kubectl.yaml
> +- connection plugin - add arguments information into censored command.
```suggestion
- connection plugin - add arguments information into censored command (https://github.com/ansible-collections/kubernetes.core/pull/196).
```

2021-08-04 12:36 UTC, gravesm approved these changes

2021-08-04 13:56 UTC, merged