add plugin_version parameter for helm_plugin module
ansible-collections/kubernetes.core pull request #226
Opened 2021-09-07 15:48 UTC by abikouo

##### SUMMARY

closes #157 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2021-09-09 08:42 UTC, abikouo commented
recheck

2021-09-27 10:34 UTC, Akasurde requested changes
Rest LGTM

2021-09-27 10:34 UTC, Akasurde commented on plugins/modules/helm_plugin.py
> +      - If C(state=latest) the Helm plugin will be updated. Added in version 2.2.0.
```suggestion
      - If C(state=latest) the Helm plugin will be updated. Added in version 2.3.0.
```

2021-09-27 10:34 UTC, Akasurde commented on plugins/modules/helm_plugin.py
> +    version_added: "2.2.0"
```suggestion
    version_added: "2.3.0"
```

2021-09-27 10:34 UTC, Akasurde commented on plugins/modules/helm_plugin.py
> +            helm_cmd_common += " " + "--version=" + plugin_version
```suggestion
            helm_cmd_common += " --version=%s" % plugin_version
```

2021-09-28 15:02 UTC, abikouo commented
@Akasurde changes requested have been resolved, could you please review/approve ? Thanks

2021-09-28 17:11 UTC, gravesm approved these changes

2021-09-29 11:06 UTC, merged