add diff output when using helfdiff
ansible-collections/kubernetes.core pull request #236
Opened 2021-09-16 15:31 UTC by joschi36

I have tried it before here: https://github.com/ansible-collections/community.kubernetes/pull/363
copied from my other PR:
##### SUMMARY
In the previous PR #355 @Akasurde has implemented optional helm check by the helm plugin diff.
I was unsure why we would not use this for --diff in Ansible. This would be very useful.
I have added a gist with a simple module I build which is actually using it.
Also, I think this PR needs some more love, but first I wanted to gather a little bit of feedback from the original creator @Akasurde and @LucasBoisserie 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

Helm

##### ADDITIONAL INFORMATION
-

2021-09-21 09:59 UTC, joschi36 commented
recheck

2021-09-27 10:31 UTC, Akasurde commented
recheck

2021-09-28 18:07 UTC, gravesm requested changes
Thanks, @joschi36, this looks good. The only thing that needs to be addressed is that we should specifically check if the user has requested a diff. You can use the  `module._diff` boolean variable to check this. If it's false, just set the diff back to an empty string.

2022-01-12 12:09 UTC, Akasurde commented
@joschi36 Could you please rebase this PR and ping me? Thanks

2022-01-17 08:01 UTC, joschi36 commented
@Akasurde Sorry that there was no movement in the last few months.

I think @jfrabaute's Pull Request https://github.com/ansible-collections/kubernetes.core/pull/290 supersedes this. Can you confirm?

2022-01-17 08:15 UTC, Akasurde commented
@joschi36 Thanks for the confirmation. It does look like #290 supersedes this PR. I will go ahead and close this.

Thanks for the contribution.

2022-01-17 08:15 UTC, closed without merging