add no_proxy support to k8s*
ansible-collections/kubernetes.core pull request #272
Opened 2021-10-26 10:03 UTC by itaru2622

##### SUMMARY

close #271

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

plugins/module_utils/args_common.py
plugins/modules/k8s*

##### ADDITIONAL INFORMATION

It requires latest kubernetes library(>=19.15.0) to use this feature.

```paste below

pip install kubernetes>=19.15.0
then, use following snippet yaml:

  - k8s:
      state: present
      src: "deployment.yaml"
      proxy:      "http://proxy.yourdomain.com:8080/"
      no_proxy:   "localhost,.yourdomain.com,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192,168.0.0/16"

or use environment variable K8S_AUTH_NO_PROXY as well as K8S_AUTH_PROXY.
```

2021-10-27 15:57 UTC, abikouo submitted a review, later dismissed
@itaru2622 I just forgot to mention that you will also need a change log to report this change.

2021-10-30 23:42 UTC, itaru2622 commented
@abikouo your comment applied. please review it.  at current, some CI tests were failed but I could imagine what should I do.

was it caused by 'version_added:2.2.2'  or do I need to fix?
I cannot imagine what is wrong because of less message in failure reason. Is there any way to test them in local?

2021-11-01 14:09 UTC, gravesm commented
@itaru2622 Since this is a new feature and not a bugfix, the version_added needs to be 2.3.0.

2021-11-01 23:44 UTC, itaru2622 commented
@gravsm Thank you for your comment. I updated version_added to 2.3.0.

2021-11-02 14:40 UTC, gravesm commented
recheck

2021-11-02 21:50 UTC, itaru2622 commented
@gravesm thank you for your help.

2021-11-03 10:15 UTC, itaru2622 commented
@gravesm @abikouo finally first CI test passed, what should I do next? could you review this, please.

2021-11-04 13:09 UTC, gravesm commented
@itaru2622 The second CI check will run once the PR is approved. Could you add a failure when the kubernetes version is not high enough? You can add it after the `for` block here if the `no_proxy` param has been set: https://github.com/ansible-collections/kubernetes.core/blob/91b80b1d1d99297090649778e89e172a13746252/plugins/module_utils/common.py#L181 See https://github.com/ansible-collections/kubernetes.core/blob/91b80b1d1d99297090649778e89e172a13746252/plugins/module_utils/common.py#L198 for how to do the failure in this function.

2021-11-05 21:58 UTC, itaru2622 commented
@gravesm thank you I will apply them

2021-11-08 07:41 UTC, itaru2622 commented
@gravesm I applied your comment, please check it.

2021-11-08 13:23 UTC, gravesm requested changes

2021-11-08 13:23 UTC, gravesm commented on plugins/module_utils/common.py
> +                if true_name == 'no_proxy' and LooseVersion(kubernetes.__version__) < LooseVersion("19.15.0"):
Could you move this down to line 221, after the `if auth_set("host")` block? It's currently only checking if NO_PROXY has been set through the environment variable. It needs to check against the `auth` dict after we're done creating it. So something like:
```
if auth_set("no_proxy") and LooseVersion...
```

2021-11-08 23:58 UTC, itaru2622 commented
@gravesm I applied your comment about kubernetes version check, and rebased to latest main branch.

2021-11-09 13:29 UTC, gravesm approved these changes
Thanks for your work on this!

2021-11-09 15:48 UTC, gravesm commented
recheck

2021-11-09 18:31 UTC, gravesm commented
recheck

2021-11-10 15:19 UTC, gravesm commented
recheck

2021-11-10 16:57 UTC, gravesm commented
recheck

2021-11-10 18:25 UTC, merged