add support for community.okd.openshift_adm_groups_sync
ansible-collections/kubernetes.core pull request #274
Opened 2021-10-28 15:48 UTC by abikouo

##### SUMMARY
new module ``community.okd.openshift_adm_group_sync`` requires action group

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2021-11-17 11:43 UTC, Akasurde approved these changes
LGTM

2021-11-17 16:25 UTC, gravesm requested changes

2021-11-17 16:25 UTC, gravesm commented on plugins/action/k8s_info.py
> +            "community.okd.openshift_adm_groups_sync",
```suggestion
            "community.okd.openshift_adm_groups_sync",
            "redhat.openshift.openshift_adm_groups_sync",
```

2021-12-06 13:43 UTC, gravesm approved these changes

2021-12-06 13:43 UTC, gravesm commented
recheck

2022-01-13 10:34 UTC, merged