add pass-credentials key
ansible-collections/kubernetes.core pull request #282
Opened 2021-11-16 09:50 UTC by nkromano

##### SUMMARY

In helm version [v3.6.1](https://github.com/helm/helm/releases/tag/v3.6.1) when downloading charts from password protected repositories that served from a different domain than the repository, need to use --pass-credentials key.

Add possibility to use the pass-credentials key in helm_repository.py

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME

helm_repository

2021-11-16 14:50 UTC, abikouo requested changes
@nkromano Thanks for taking the to submit this PR.
You need to attach a changelog.

2021-11-16 14:50 UTC, abikouo commented on plugins/modules/helm_repository.py
> +    type: boolean
```suggestion
    type: boolean
    version_added: 2.3.0
```

2021-11-16 14:50 UTC, abikouo commented on plugins/modules/helm_repository.py
> +            pass_credentials=dict(type="bool", default=False)
```suggestion
            pass_credentials=dict(type="bool", default=False),
```

2021-11-17 10:07 UTC, nkromano commented
Hello, @abikouo.
Thanks for comments.
Done.

2021-11-17 11:38 UTC, Akasurde submitted a review, later dismissed

2021-11-17 11:38 UTC, Akasurde commented on CHANGELOG.rst
> +
Changelog.rst is autogenerated. 
Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment). See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

2021-11-17 11:38 UTC, Akasurde commented on plugins/modules/helm_repository.py
> +    type: boolean
```suggestion
    type: bool
```

2021-11-17 14:23 UTC, gravesm reviewed
Looks like the black formatting check is failing for two lines. Otherwise, looks good. Thanks!

2021-11-17 14:23 UTC, gravesm commented on plugins/modules/helm_repository.py
> +    command, repository_name, repository_url, repository_username, repository_password, pass_credentials
```suggestion
    command,
    repository_name,
    repository_url,
    repository_username,
    repository_password,
    pass_credentials,
```

2021-11-17 14:23 UTC, gravesm commented on plugins/modules/helm_repository.py
> +                helm_cmd, repo_name, repo_url, repo_username, repo_password, pass_credentials
```suggestion
                helm_cmd,
                repo_name,
                repo_url,
                repo_username,
                repo_password,
                pass_credentials,
```

2021-11-18 14:15 UTC, nkromano commented
Hello, @gravesm!
Done.

2021-11-18 15:12 UTC, gravesm reviewed
There are still two trailing commas missing which is causing the black check to fail. Once these are fixed and CI passes we can get this merged.

2021-11-18 15:12 UTC, gravesm commented on plugins/modules/helm_repository.py
> +    pass_credentials
```suggestion
    pass_credentials,
```

2021-11-18 15:12 UTC, gravesm commented on plugins/modules/helm_repository.py
> +                pass_credentials
```suggestion
                pass_credentials,
```

2021-11-18 17:35 UTC, gravesm commented
recheck

2021-11-19 06:16 UTC, Akasurde commented
recheck

2021-11-19 15:35 UTC, gravesm commented
recheck

2021-11-19 17:01 UTC, gravesm approved these changes

2021-11-19 18:20 UTC, merged