Adding sleep 0 as workaround when copying files with kubectl exec
ansible-collections/kubernetes.core pull request #321
Opened 2022-01-05 15:51 UTC by Ronko370

using dd, therefore copying file will not be terminated
before it has completed.

##### SUMMARY
For all the commands executed remotely,  ** && sleep 0** will be appended as a workaround for all the commands to terminate properly:

https://github.com/ansible/ansible/blob/16def8050a38510fe3e477a943a90a47a1bf3c8a/lib/ansible/plugins/action/__init__.py#L1243

Workaround will be applied in case of **kubectl exec** too:

https://github.com/ansible-collections/kubernetes.core/blob/b19ff9d70a6ad2efc17a995edf3f348deb67d603/plugins/connection/kubectl.py#L300 

That is not the case in case of the file copy executed by using **kubectl exec**, therefore it is possible for the **kubectl exec** to terminate before **dd** finishes properly causing the file to be truncated.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
kubectl

##### ADDITIONAL INFORMATION
N/A

2022-01-12 08:15 UTC, Akasurde requested changes
Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment). See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

2022-01-25 13:32 UTC, gravesm commented
recheck

2022-02-03 00:26 UTC, goneri commented
recheck

2022-02-03 01:21 UTC, goneri commented
recheck

2022-02-03 01:32 UTC, goneri commented
recheck

2022-02-04 13:53 UTC, abikouo commented
recheck

2022-02-04 19:10 UTC, goneri commented
recheck

2022-02-10 05:58 UTC, Akasurde commented
recheck

2022-02-12 14:10 UTC, Akasurde commented
superseded by https://github.com/ansible-collections/kubernetes.core/pull/378

Due to a change in the CI infra, I migrated this PR to #378. Thanks for the contribution.

2022-02-12 14:10 UTC, closed without merging