Added missing kubeconfig parameter to helm_cmd_common
ansible-collections/kubernetes.core pull request #357
Opened 2022-02-01 18:17 UTC by suppaduppax

--kubeconfig kubeconfig was not being appended to the helm command. 
This is a propsed fix, although I'm not sure if the correct location for it would be in helm_cmd_common. release_status() requires it right away so I added it to help_cmd_common rather than adding a kubeconfig parameter to each function requiring kubeconfig

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2022-02-02 04:19 UTC, Akasurde requested changes

2022-02-02 04:19 UTC, Akasurde commented on plugins/modules/helm.py
> +    if kubeconfig:
@suppaduppax Thanks for the contribution. This is already handled in [here](https://github.com/ansible-collections/kubernetes.core/blob/b54e9ef4ef36e8da5a9a30b0c2d39232c2773aa8/plugins/module_utils/helm.py#L48). So I think this check is irrelevant.

2022-02-03 00:27 UTC, goneri commented
recheck

2022-02-03 00:38 UTC, goneri commented
recheck

2022-02-03 01:21 UTC, goneri commented
recheck

2022-02-03 01:28 UTC, goneri commented
recheck

2022-02-03 01:51 UTC, goneri commented
recheck

2022-02-04 19:07 UTC, goneri commented
recheck

2022-04-22 12:17 UTC, gravesm commented
I'm going to close this one as the module already correctly uses the specified kubeconfig. It is temporarily set on the environment. If you find that it is not doing this, feel free to open an issue with steps to reproduce the problem.

2022-04-22 12:17 UTC, closed without merging