WIP - Remove ``omit`` value from template args
ansible-collections/kubernetes.core pull request #432
Opened 2022-04-11 12:25 UTC by abikouo

##### SUMMARY

While defining resource using ``template`` parameter, the code does not remove the ``omit`` value if any.
This fix adds a post process to remove any omit value from the resource definition.
fixes #431 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

k8s*

2022-04-13 11:06 UTC, gravesm approved these changes

2022-04-14 03:57 UTC, Akasurde requested changes
Minor nit-picks. Rest LGTM

2022-04-14 03:57 UTC, Akasurde commented on changelogs/fragments/432-fix-issue-when-using-template-parameter.yaml
> +  - Remove omit place holder when defining resource using template parameter. (https://github.com/ansible-collections/kubernetes.core/issues/431).
```suggestion
  - Remove `omit` placeholder when defining resource using template parameter (https://github.com/ansible-collections/kubernetes.core/issues/431).
```

2022-04-14 03:57 UTC, Akasurde commented on plugins/action/k8s_info.py
> +            return data
Can this code be written as following - 

```suggestion
        if isinstance(data, dict):
            result = dict()
            for key, value in iteritems(data):
                if value == self.omit:
                    continue
                result[key] = self.remove_omit(value)
            return result
        if isinstance(data, list):
            return [self.remove_omit(v) for v in data if v != self.omit]
        return data
```

2022-04-14 03:57 UTC, Akasurde commented on tests/unit/action/test_remove_omit.py
> +    # print(result)
```suggestion
```

2022-04-14 05:47 UTC, Akasurde approved these changes

2022-04-14 06:15 UTC, merged