helm_registry_auth module to authenticate in OCI registry
ansible-collections/kubernetes.core pull request #800
Opened 2024-11-29 14:11 UTC by yurnov

##### SUMMARY
The new module helm_registry_auth module support login and logout to OCI registry (`helm registry login` and `helm registry logout` command)

It's addressed issue #578 

##### ISSUE TYPE

- New Module Pull Request

##### COMPONENT NAME
helm_registry_auth

##### ADDITIONAL INFORMATION

Similar was started as #601 but it wasn't completed for a while. Module in this PR is already used in my lab environment. 

PR include a changelog, documentation and integration tests.

2024-11-29 16:15 UTC, yurnov commented
Hi @gravesm @abikouo,

it seems that Kubevirt tests failed for a reason that is not related to this PR. Could you please check? And also review this PR.

2024-12-11 14:46 UTC, yurnov commented on plugins/modules/helm_registry_auth.py
> +        module.exit_json(changed=changed)
> I would include the `helm_cmd` here.

do you mean to have it output? Will do

2024-12-11 15:04 UTC, yurnov commented on changelogs/fragments/20241116-helm_registry_auth.yaml
Hi @gravesm, I removed the fragment and [changelog / Require a changelog](https://github.com/ansible-collections/kubernetes.core/actions/runs/12279018967/job/34262069268?pr=800#logs) rule failed, we have two options, to return changelog, or to add `skip-changelog` label.

2024-12-11 16:19 UTC, abikouo requested changes

2024-12-11 16:51 UTC, yurnov commented on plugins/module_utils/helm.py
> +    def run_helm_command(self, command, fails_on_error=True, data=None):
it's quite an old version of the helm, probably I should add into the requirement of new module helm>=3.0.0?

Anyway, I made this change

2024-12-12 10:26 UTC, abikouo requested changes
Some minor changes

2024-12-12 10:26 UTC, abikouo commented on plugins/modules/helm_registry_auth.py
> +    rc, out, err = module.run_helm_command(helm_cmd, data=password)
```suggestion
    rc, out, err = module.run_helm_command(helm_cmd, data=password, fails_on_error=False)
```
This is needed to ensure the idempotency of the log-out operation

2024-12-12 10:26 UTC, abikouo commented on tests/integration/targets/helm_registry_auth/tasks/main.yaml
> +        that: "'Removing login credentials' in _helm_registry_auth_logout.stderr"
```suggestion
    - name: Test logout
      helm_registry_auth:
        registry: localhost:{{ registry_port }}
        state: absent
      register: _helm_registry_auth_logout

    - name: Assert logout
      # Helm binary prints the message to stderr
      assert:
        that: "'Removing login credentials' in _helm_registry_auth_logout.stderr"
   
   - name: Test logout idempotency
      helm_registry_auth:
        registry: localhost:{{ registry_port }}
        state: absent
      register: _helm_registry_auth_logout_idempotency

    - name: Assert logout operation did not report change
      ansible.builtin.assert:
        that: _helm_registry_auth_logout_idempotency is not changed
```

2024-12-12 11:18 UTC, yurnov commented on tests/integration/targets/helm_registry_auth/tasks/main.yaml
> +        that: "'Removing login credentials' in _helm_registry_auth_logout.stderr"
thanks for suggestion, done

2024-12-12 14:44 UTC, abikouo commented
@yurnov, another thing: integration tests are not running because the following file is missing: `tests/integration/targets/helm_registry_auth/aliases`. Please add it with the following content: `time=16`. It seems this is the estimated time for the target to run.

2024-12-12 14:58 UTC, yurnov commented
> @yurnov, another thing: integration tests are not running because the following file is missing: `tests/integration/targets/helm_registry_auth/aliases`. Please add it with the following content: `time=16`. It seems this is the estimated time for the target to run.

Done

2024-12-12 15:40 UTC, yurnov commented
Finally, integration test fixed

2024-12-12 15:45 UTC, abikouo approved these changes

2024-12-14 09:11 UTC, yurnov commented
Merged `main` to PR to bring #827 (fix for helm tests)

2024-12-17 11:20 UTC, yurnov commented
> @yurnov CI is stable now, could you please rebase your PR and address merge conflicts? Thanks

Sure, I just did this.

Thanks for your valuable help. May I ask you also to review PR #831 and add a `skip-changelog` label as it trivial documendation-only change?

2024-12-17 14:39 UTC, merged