add reset_then_reuse_values support to helm module
ansible-collections/kubernetes.core pull request #802
Opened 2024-11-30 09:50 UTC by b0z02003

##### SUMMARY
Starting with version 3.14.0, Helm supports `--reset-then-reuse-values`. As discussed on the [original PR](https://github.com/helm/helm/issues/8085). This greatly improves on `--reuse-values` as it allows to avoid templates errors when new features are added to an upgraded chart.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
helm

##### ADDITIONAL INFORMATION
This PR is greatly 'inspired' by #575 and because I wasn't sure how I could provide additional tests for it, I actually copied those build previously for `--reuse-values` (as it is an improvement on this feature.

2024-12-17 10:57 UTC, abikouo requested changes
@b0z02003 Thanks for submitting this PR. 
In addition to the requested changes, you must include the new test files in `main.yml` of the corresponding integration test targets.

2024-12-17 10:57 UTC, abikouo commented on plugins/modules/helm.py
> +      - If I(reset_values) or I(reuse_values) is set to C(True), this is ignored.
```suggestion
        parameters O(release_values), O(values_files) or O(set_values).
      - If O(reset_values) or O(reuse_values) is set to V(True), this is ignored.
      - This feature requires helm diff >= 3.9.12.
```

2024-12-17 10:57 UTC, abikouo commented on plugins/modules/helm.py
> +        deploy_command += " --reset-then-reuse-values"
```suggestion
    if reset_then_reuse_values:
        helm_diff_version = get_plugin_version("diff")
        if LooseVersion(helm_diff_version) < LooseVersion("3.9.12"):
            module.warn("helm diff support option --reset-then-reuse-values starting release >= 3.9.12")
        else:
            deploy_command += " --reset-then-reuse-values"
```

2024-12-17 16:22 UTC, b0z02003 commented
@abikouo Thanks for the suggestions ! I've tried to improve on them to also check for helm version and added the integration tests (that was a big oversight on my part, my bad).

2024-12-19 14:59 UTC, abikouo reviewed
This will address linters issues

2024-12-19 14:59 UTC, abikouo commented on plugins/modules/helm.py
> +            module.warn("helm support option --reset-then-reuse-values starting release >= 3.14.0")
```suggestion
            module.warn(
                "helm support option --reset-then-reuse-values starting release >= 3.14.0"
            )
```

2024-12-19 14:59 UTC, abikouo commented on plugins/modules/helm.py
> +            module.warn("helm support option --reset-then-reuse-values starting release >= 3.14.0")
```suggestion
            module.warn(
                "helm support option --reset-then-reuse-values starting release >= 3.14.0"
            )
```

2024-12-19 14:59 UTC, abikouo commented on plugins/modules/helm.py
> +            module.warn("helm diff support option --reset-then-reuse-values starting release >= 3.9.12")
```suggestion
            module.warn(
                "helm diff support option --reset-then-reuse-values starting release >= 3.9.12"
            )
```

2025-01-06 17:37 UTC, abikouo commented
@b0z02003 Some tests are failing because you need to rebase your branch with the `main` branch. However, you'll also need to fix the new tests you introduced.

2025-01-18 18:38 UTC, yurnov commented
I see some race conditions:
```
TASK [helm : Initial chart installation] ***************************************
task path: /home/runner/collections/ansible_collections/kubernetes/core/tests/integration/targets/helm/tasks/test_helm_reset_then_reuse_values.yml:17
Saturday 18 January 2025  18:31:30 +0000 (0:00:00.039)       0:03:29.157 ****** 
......
fatal: [localhost]: FAILED! => {
    "changed": false,
    "command": "/tmp/helm/linux-amd64/helm upgrade -i --reset-values --create-namespace -f=/tmp/tmpvpofk4e1.yml test-redis 'oci://registry-1.docker.io/bitnamicharts/redis'",
    "invocation": {
        "module_args": {
            "api_key": null,
            "atomic": false,
            "binary_path": "/tmp/helm/linux-amd64/helm",
            "ca_cert": null,
            "chart_ref": "oci://registry-1.docker.io/bitnamicharts/redis",
            "chart_repo_url": null,
            "chart_version": null,
            "context": null,
            "create_namespace": true,
            "dependency_update": false,
            "disable_hook": false,
            "force": false,
            "history_max": null,
            "host": null,
            "kubeconfig": null,
            "post_renderer": null,
            "purge": true,
            "release_name": "test-redis",
            "release_namespace": "helm-reuse-values",
            "release_state": "present",
            "release_values": {
                "master": {
                    "count": 1,
                    "kind": "Deployment"
                },
                "replica": {
                    "replicaCount": 3
                }
            },
            "replace": false,
            "reset_then_reuse_values": false,
            "reset_values": true,
            "reuse_values": null,
            "set_values": null,
            "skip_crds": false,
            "timeout": null,
            "update_repo_cache": false,
            "validate_certs": true,
            "values_files": [],
            "wait": false,
            "wait_timeout": null
        }
    },
    "msg": "Failure when executing Helm command. Exited 1.\nstdout: \nstderr: Error: UPGRADE FAILED: create: failed to create: secrets \"sh.helm.release.v1.test-redis.v3\" is forbidden: unable to create new content in namespace helm-reuse-values because it is being terminated\n",
    "stderr": "Error: UPGRADE FAILED: create: failed to create: secrets \"sh.helm.release.v1.test-redis.v3\" is forbidden: unable to create new content in namespace helm-reuse-values because it is being terminated\n",
    "stderr_lines": [
        "Error: UPGRADE FAILED: create: failed to create: secrets \"sh.helm.release.v1.test-redis.v3\" is forbidden: unable to create new content in namespace helm-reuse-values because it is being terminated"
    ],
    "stdout": "",
    "stdout_lines": []
}
```

2025-01-18 23:20 UTC, yurnov commented
> I see some race conditions:

I have fixed this race condition and all other parts of the integration test for this PR and added a test to ensure that a warning appears in case of older versions of Helm and Helm diff, so the CI part is fully OK. 

However, I still have a not resolved question:
https://github.com/b0z02003/kubernetes.core/blob/baed9a658fa538476d415978406c1cd579fe83d3/plugins/modules/helm.py#L540C1-L547C59

Should we have just a warning message and skips of the unsupported option `--reset-then-reuse-values` here? It potentially may lead to unexpected results with just warning that easy to didn't catch in CI/automation, so, probably it better to have something like:

```
    if reset_then_reuse_values:
        helm_version = module.get_helm_version()
        if LooseVersion(helm_version) < LooseVersion("3.14.0"):
            module.warn(
                msg='helm support option --reset-then-reuse-values starting release >= 3.14.0',
                **opt_result
            )
        else:
            deploy_command += " --reset-then-reuse-values"
```

And same here:
https://github.com/b0z02003/kubernetes.core/blob/baed9a658fa538476d415978406c1cd579fe83d3/plugins/modules/helm.py#L700C1-L712C48

I'm not sure, looking for suggestions from repo maintainers and @b0z02003.

Att @gravesm, @abikouo

2025-01-18 23:30 UTC, yurnov commented on plugins/modules/helm.py
> +            module.warn(
it it ok to have working, or better to change to fail like:
```
            module.fail_json(
                msg='helm support option --reset-then-reuse-values starting release >= 3.14.0',
                **opt_result
```

just to avoid a case when helm will runs without `--reset-then-reuse-values` with unexpected result in CI

2025-01-18 23:30 UTC, yurnov commented on plugins/modules/helm.py
> +            module.warn(
same here

2025-01-19 11:22 UTC, b0z02003 commented on plugins/modules/helm.py
> +            module.warn(
You are right, we should fail when trying to use that kind of unsupported feature, I'll update the PR accordingly.

2025-01-19 12:26 UTC, yurnov commented
Hi @b0z02003, you committed to testing in CI https://github.com/ansible-collections/kubernetes.core/actions/runs/12853271360/job/35836239457, and all tests passed.

2025-01-19 12:31 UTC, yurnov commented on plugins/modules/helm.py
> +        if LooseVersion(helm_diff_version) < LooseVersion("3.9.12"):
I see a case when both requirement aren't meet, the only fist check will be executed and only `reset_then_reuse_values requires helm diff >= 3.9.12, current version is {0}` will be on fail message. 

So, it better to check both conditions and have a message that contains helm, helm diff or both, depends on versions installed.

If you don't mind, I will prepare commit that improve this part

2025-01-19 12:37 UTC, yurnov commented
Hi @abikouo, @gravesm,

would you please review this PR? The integration test is completed here.

2025-04-24 18:03 UTC, yurnov commented
Hi @abikouo, @beeankha,
Would you please review this PR? It was completed before the 5.2 release, except for some small cosmetic changes, and it seems to be finally ready. I rebased PR (actually merged main to it) and regenerated rst file (only for the module that changed).

2025-04-25 15:50 UTC, beeankha approved these changes

2025-04-28 14:51 UTC, abikouo approved these changes

2025-04-28 15:11 UTC, merged