support merge_type``json``
ansible-collections/kubernetes.core pull request #83
Opened 2021-04-23 14:55 UTC by abikouo

##### SUMMARY

support merge_type ``json``

#54 
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

k8s
##### ADDITIONAL INFORMATION

```paste below
- name: Patch Nginx deployment to support ssl-passthough
  kubernetes.core.k8s:
    kind: Deployment
    namespace: "{{ k8s_ns }}"
    name: "{{ k8s_deployment_name }}"
    merge_type: 
    - json
    definition:
    - op: add
      path: '/spec/template/spec/containers/0/args/-'
      value: '--enable-ssl-passthrough'
```

2021-04-23 18:17 UTC, gravesm requested changes
Thanks @abikouo! In addition to my comments we need to add jsonpatch to requirements.txt and update the requirements for the k8s module.

2021-04-23 18:17 UTC, gravesm commented on molecule/default/tasks/merge_types.yml
> +      - describe_depl.resources[0].spec.template.spec.containers[0].args | length == 4
Could you also add some tests for `merge_type: merge`?

2021-04-23 19:47 UTC, abikouo commented on molecule/default/converge.yml
> +          tags: [ merge_type, k8s ]
agree

2021-04-23 19:49 UTC, abikouo commented on molecule/default/tasks/merge_types.yml
> +- name: Define common facts
I was thinking we are running in a crash and burn env, 
but will do it

2021-04-23 19:53 UTC, abikouo commented
> Thanks @abikouo! In addition to my comments we need to add jsonpatch to requirements.txt and update the requirements for the k8s module.

I am just wondering as there are some module that are not set as required, as they correspond to a specific functionality
for instance ``yaml`` is used almost everywhere, should this be part of the requirements.txt to ? Just need to clarify the policy

2021-04-23 20:27 UTC, gravesm commented on molecule/default/tasks/merge_types.yml
> +- name: Define common facts
In CI it's fine, but it depending on how people have things set up locally, it makes it easier.

2021-04-23 20:29 UTC, gravesm commented
Yeah, I guess I'm not sure why yaml is not in there. I think jsonpatch should be though, because otherwise the version of k8s that goes into the EE won't be able to use this functionality.

2021-04-26 13:45 UTC, gravesm approved these changes
@Akasurde can you take a look at this?

2021-04-28 13:03 UTC, goneri commented on .github/workflows/ci.yml
> +        run: pip install ansible "molecule<3.3.0" yamllint openshift flake8 jsonpatch
jsonpatch should also be in `requirements.txt`.

2021-04-28 13:05 UTC, goneri commented on .github/workflows/ci.yml
> +        run: pip install ansible "molecule<3.3.0" yamllint openshift flake8 jsonpatch
My bad, it's already the case :-).

2021-04-28 13:06 UTC, goneri approved these changes

2021-04-28 13:06 UTC, merged

2021-04-28 13:07 UTC, goneri commented
Nice patch, thanks @abikouo.